"""fix_user_progress_relationships

Revision ID: 8f43c6f50c0d
Revises: 718a92860356
Create Date: 2025-03-15 19:44:10.478157+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f43c6f50c0d'
down_revision: Union[str, None] = '718a92860356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress_poi_association', 'progress_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress_poi_association', 'poi_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('progress_poi_association_progress_id_fkey', 'progress_poi_association', type_='foreignkey')
    op.drop_constraint('progress_poi_association_poi_id_fkey', 'progress_poi_association', type_='foreignkey')
    op.create_foreign_key(None, 'progress_poi_association', 'user_progress', ['progress_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'progress_poi_association', 'points_of_interest', ['poi_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress_poi_association', type_='foreignkey')
    op.drop_constraint(None, 'progress_poi_association', type_='foreignkey')
    op.create_foreign_key('progress_poi_association_poi_id_fkey', 'progress_poi_association', 'points_of_interest', ['poi_id'], ['id'])
    op.create_foreign_key('progress_poi_association_progress_id_fkey', 'progress_poi_association', 'user_progress', ['progress_id'], ['id'])
    op.alter_column('progress_poi_association', 'poi_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('progress_poi_association', 'progress_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
