"""add_metadata_column_to_regions

Revision ID: 7cb03a408134
Revises: 3dbcc5965512
Create Date: 2025-03-14 17:50:29.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb03a408134'
down_revision: Union[str, None] = '3dbcc5965512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('region_metadata', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'region_metadata')
    # ### end Alembic commands ###
